# Configuration du thÃ¨me
[theme]
primaryColor = "#4CAF50"  # Vert vif Ã©voquant la nature
backgroundColor = "#FFF8E1"  # Jaune pÃ¢le comme couleur de fond
secondaryBackgroundColor = "#A5D6A7"  # Vert clair comme couleur secondaire
textColor = "#3E2723"  # Marron foncÃ© pour le texte
font = "Roboto, sans-serif"  # Police Roboto ou sans-serif

# IcÃ´nes d'animaux pour les diffÃ©rentes sections de l'application
[icons]
collecte_responses = "ğŸ¾"
delete_response = "ğŸ—‘ï¸"
delete_all_responses = "ğŸ—‘ï¸ğŸ—‘ï¸"
display_responses = "ğŸ“‹"
filter_responses = "ğŸ”"
visualize_pet_preference = "ğŸ“Š"

# Configuration des dÃ©prÃ©ciations
[deprecation]
showPyplotGlobalUse = false  # DÃ©sactiver l'affichage des utilisations globales de pyplot
